In [1]:
import gensim
import pandas as pd
from gensim.models import Word2Vec

In [2]:
data = pd.read_csv("info.csv")

In [3]:
asana_dataset = pd.read_csv('Book1.csv')

In [4]:
data

Benefits  \
0   Positive effects on the musculoskeletal system...   
1   makes your shoulders, wrists and arms strong. ...   
2   Back bending will strengthen your back and abd...   
3   Tones and Better Blood Circulation: The practi...   
4   Strengthens the quadriceps, gluteus maximus, a...   
5   Strengthens ankles, knees and legs.Roots thigh...   
6   It is a great posture and exercise for arm bal...   
7   Develops nervous control.Reverses the flow of ...   
8   Strengthens and improves flexibility in the in...   
9   Arms strengthen, core to help hold you up,glut...   
10  The balasana yoga or the asana helps release a...   
11  Practicing Bhairavasana lengthens the spine wh...   
12  Relieves pain and stiffness in the neck, shoul...   
13  Opens up the hip joints.Provides deep stretch ...   
14  Bhujangasana is very useful to keep your back ...   
15  Practicing Bhujapidasana can build strength in...   
16  Improves the flexibility of the spine. Improve...   
17  Similar to plank exercises, this asana aligns ...   
18  This seated posture strengthens the back muscl...   
19  In this asana, back bending will strengthen yo...   
20  This pose is a part of Hatha yoga that improve...   
21  relieves depression, relieves anxiety,  reliev...   
22  Rejuvenates the spine, Improves spinal flexibi...   
23  High Blood Pressure, anxiety,  relieves fatigu...   
24  relieves lower back tightness, relieves lower ...   
25  High Blood Pressure, anxiety,  relieves fatigu...   
26   anxiety,  relieves fatigue, improves posture ...   
27  High Blood Pressure, anxiety,  relieves fatigu...   
28  This energy-boosting pose stretches your chest...   
29  Crow Pose and Crane Pose improve focus, and st...   
30  Boosts confidence and helps treat depression, ...   
31  Improves the digestive system.Strengthens the ...   
32  Strengthens and improves flexibility in the in...   
33  This seated posture strengthens the back muscl...   
34  Strengthens the back muscles\nRelieves the tir...   
35  Arms strengthen, core to help hold you up,glut...   
36  Feathered Peacock improves postural and body a...   
37  This asana induces relaxation and alleviates t...   

                                            Yoga-Asan  
0                               Adho Mukha Shvanasana  
1                              Adho Mukha Vrikshasana  
2                                  Akarna Dhanurasana  
3                                          Anantasana  
4                                        Anjaneyasana  
5                                   Ardha Chandrasana  
6                                  Ashtanga Namaskara  
7                                       Astavakrasana  
8                         Baddha Konasana/ Bhadrasana  
9                                  Bakasana/ Kakasana  
10                                           Balasana  
11                          Bhairavasana/ Ankushasana  
12                                     Bharadvajasana  
13                                          Bhekasana  
14                                       Bhujangasana  
15                                      Bhujapidasana  
16                           Bidalasana/ Marjariasana  
17                              Chaturanga/ Dandasana  
18                                          Dandasana  
19                                        Dhanurasana  
20                                        Durvasasana  
21                   Dwi Hasta Kulpa Janu Shirshasana  
22                           Paripurna Matsyendrasana  
23                                       Marichyasana  
24                          Ardha Mula Matsyendrasana  
25                              Adho Mukha Shvanasana  
26                            Urdhva Mukha Shvanasana  
27                                     Chamatkarasana  
28                                 Urdhva Dhanurasana  
29                                           Bakasana  
30                   Tadasana Urdhva Baddha Hastasana  
31  Parivritta Namaskar Stiti

In [5]:
asana_dataset['asanas']

0         Shvanasana
1        Vrikshasana
2        Dhanurasana
3         Anantasana
4       Anjaneyasana
5        Chandrasana
6          Namaskara
7      Astavakrasana
8           Konasana
9           Kakasana
10          Balasana
11       Ankushasana
12    Bharadvajasana
13         Bhekasana
14      Bhujangasana
15     Bhujapidasana
16        Bidalasana
17        Chaturanga
18         Dandasana
19       Dhanurasana
20       Durvasasana
21       Shirshasana
22    Matsyendrasana
23      Marichyasana
24    Matsyendrasana
25        Shvanasana
26        Shvanasana
27    Chamatkarasana
28       Dhanurasana
29          Bakasana
30         Hastasana
31        Muktyasana
32         Padmasana
33         Dandasana
34        Bandhasana
35      Sarvangasana
36        Mayurasana
37       Gomukhasana
Name: asanas, dtype: object

In [6]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
corpus = []
for i in range(0, 38):
  processed_data = re.sub('[^a-zA-Z]', ' ', data['Benefits'][i])
  processed_data = processed_data.lower()
  processed_data = processed_data.split()
  all_stopwords = stopwords.words('english')
  processed_data = [word for word in processed_data if not word in set(all_stopwords)]
  processed_data = ' '.join(processed_data)
  corpus.append(processed_data)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [7]:
for i in range(0,38):
  data['Benefits'][i] = corpus[i]

In [8]:
data

Benefits  \
0   positive effects musculoskeletal system stretc...   
1   makes shoulders wrists arms strong enhances se...   
2   back bending strengthen back abdominal muscles...   
3   tones better blood circulation practice ananth...   
4   strengthens quadriceps gluteus maximus hamstri...   
5   strengthens ankles knees legs roots thighbones...   
6   great posture exercise arm balancing increases...   
7   develops nervous control reverses flow apana d...   
8   strengthens improves flexibility inner thighs ...   
9   arms strengthen core help hold glutes adductor...   
10  balasana yoga asana helps release tension ches...   
11  practicing bhairavasana lengthens spine stretc...   
12  relieves pain stiffness neck shoulders lower b...   
13  opens hip joints provides deep stretch legs mu...   
14  bhujangasana useful keep back healthy fit asan...   
15  practicing bhujapidasana build strength arms s...   
16  improves flexibility spine improves prana body...   
17  similar plank exercises asana aligns whole bod...   
18  seated posture strengthens back muscles improv...   
19  asana back bending strengthen back abdominal m...   
20  pose part hatha yoga improves mind body coordi...   
21  relieves depression relieves anxiety relieves ...   
22  rejuvenates spine improves spinal flexibility ...   
23  high blood pressure anxiety relieves fatigue i...   
24  relieves lower back tightness relieves lower b...   
25  high blood pressure anxiety relieves fatigue i...   
26  anxiety relieves fatigue improves posture impr...   
27  high blood pressure anxiety relieves fatigue i...   
28  energy boosting pose stretches chest lungs als...   
29  crow pose crane pose improve focus stretch but...   
30  boosts confidence helps treat depression relie...   
31  improves digestive system strengthens abdomina...   
32  strengthens improves flexibility inner thighs ...   
33  seated posture strengthens back muscles improv...   
34  strengthens back muscles relieves tired back i...   
35  arms strengthen core help hold glutes adductor...   
36  feathered peacock improves postural body aware...   
37  asana induces relaxation alleviates tiredness ...   

                                            Yoga-Asan  
0                               Adho Mukha Shvanasana  
1                              Adho Mukha Vrikshasana  
2                                  Akarna Dhanurasana  
3                                          Anantasana  
4                                        Anjaneyasana  
5                                   Ardha Chandrasana  
6                                  Ashtanga Namaskara  
7                                       Astavakrasana  
8                         Baddha Konasana/ Bhadrasana  
9                                  Bakasana/ Kakasana  
10                                           Balasana  
11                          Bhairavasana/ Ankushasana  
12                                     Bharadvajasana  
13                                          Bhekasana  
14                                       Bhujangasana  
15                                      Bhujapidasana  
16                           Bidalasana/ Marjariasana  
17                              Chaturanga/ Dandasana  
18                                          Dandasana  
19                                        Dhanurasana  
20                                        Durvasasana  
21                   Dwi Hasta Kulpa Janu Shirshasana  
22                           Paripurna Matsyendrasana  
23                                       Marichyasana  
24                          Ardha Mula Matsyendrasana  
25                              Adho Mukha Shvanasana  
26                            Urdhva Mukha Shvanasana  
27                                     Chamatkarasana  
28                                 Urdhva Dhanurasana  
29                                           Bakasana  
30                   Tadasana Urdhva Baddha Hastasana  
31  Parivritta Namaskar Stiti

In [9]:
final = data.Benefits.apply(gensim.utils.simple_preprocess) #Convert a document into a list of lowercase tokens, ignoring tokens that are too short or too long.

In [10]:
final

0     [positive, effects, musculoskeletal, system, s...
1     [makes, shoulders, wrists, arms, strong, enhan...
2     [back, bending, strengthen, back, abdominal, m...
3     [tones, better, blood, circulation, practice, ...
4     [strengthens, quadriceps, gluteus, maximus, ha...
5     [strengthens, ankles, knees, legs, roots, thig...
6     [great, posture, exercise, arm, balancing, inc...
7     [develops, nervous, control, reverses, flow, a...
8     [strengthens, improves, flexibility, inner, th...
9     [arms, strengthen, core, help, hold, glutes, a...
10    [balasana, yoga, asana, helps, release, tensio...
11    [practicing, bhairavasana, lengthens, spine, s...
12    [relieves, pain, stiffness, neck, shoulders, l...
13    [opens, hip, joints, provides, deep, stretch, ...
14    [bhujangasana, useful, keep, back, healthy, fi...
15    [practicing, bhujapidasana, build, strength, a...
16    [improves, flexibility, spine, improves, prana...
17    [similar, plank, exercises, asana, aligns,

In [11]:
len(final)

38

In [12]:
connected_dataset = [] #list of asanas Asanas according to the respective number of cleaned words.

In [13]:
for i in range(len(final)):
  for j in range(len(final[i])):
    connected_dataset.append(asana_dataset['asanas'][i])

In [14]:
len(connected_dataset)

826

In [15]:
connected_dataset

['Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Shvanasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Vrikshasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Dhanurasana',
 'Anantasana',
 'Anantasana',
 'Anantasana',
 'Anantasana',
 'Anantasana',
 'Anantasana',
 'Anantasan

In [16]:
model = Word2Vec(sentences = final, sg=1, min_count=1, workers=4, window = 5, size = 32)

In [17]:
model.train(final, total_examples=model.corpus_count, epochs=1000)

(529470, 826000)

In [18]:
model.wv['peacock']

array([-1.1930896 ,  0.25441438, -0.40470544,  0.12316014, -0.9836359 ,
        0.63438654,  0.6004929 ,  0.9193934 , -0.18876122,  0.19697443,
       -0.09551071,  1.127051  ,  0.09923577, -0.94688296, -0.54910517,
       -0.6908234 ,  0.18025811,  0.25247133, -0.4351236 , -0.01446969,
       -1.0077295 ,  0.7170416 ,  0.8104901 ,  0.00421384, -1.4159031 ,
        1.0519634 , -1.1560403 , -0.58158475, -1.4788368 , -0.64733666,
        1.268655  ,  0.06897409], dtype=float32)

In [19]:
len(model.wv.vocab)

307

In [20]:
final

0     [positive, effects, musculoskeletal, system, s...
1     [makes, shoulders, wrists, arms, strong, enhan...
2     [back, bending, strengthen, back, abdominal, m...
3     [tones, better, blood, circulation, practice, ...
4     [strengthens, quadriceps, gluteus, maximus, ha...
5     [strengthens, ankles, knees, legs, roots, thig...
6     [great, posture, exercise, arm, balancing, inc...
7     [develops, nervous, control, reverses, flow, a...
8     [strengthens, improves, flexibility, inner, th...
9     [arms, strengthen, core, help, hold, glutes, a...
10    [balasana, yoga, asana, helps, release, tensio...
11    [practicing, bhairavasana, lengthens, spine, s...
12    [relieves, pain, stiffness, neck, shoulders, l...
13    [opens, hip, joints, provides, deep, stretch, ...
14    [bhujangasana, useful, keep, back, healthy, fi...
15    [practicing, bhujapidasana, build, strength, a...
16    [improves, flexibility, spine, improves, prana...
17    [similar, plank, exercises, asana, aligns,

In [21]:
model.wv.word_vec('pain') #another way to get embeddings of a word.

array([-0.9048441 , -0.5164918 ,  0.4251148 , -0.04966326, -0.35435683,
       -0.9933572 ,  0.07834414, -0.46734032,  0.37291723, -0.88784313,
        0.7980336 ,  0.39848676, -0.17991734, -0.60713357,  1.4567273 ,
        1.6070306 ,  0.4561262 , -0.14254999, -0.42534345,  0.59821624,
       -0.79765445,  1.5985252 , -0.6153358 ,  0.5582263 , -0.17120564,
       -0.7989929 ,  0.7456789 ,  1.4397846 ,  0.4617833 , -1.4826574 ,
       -0.71463364, -0.5288116 ], dtype=float32)

In [22]:
final[0][0]

'positive'

In [23]:
model.wv.most_similar("depression", topn = 10 )

[('boosts', 0.7781588435173035),
 ('arthritis', 0.7740115523338318),
 ('thyroid', 0.7362685203552246),
 ('fingers', 0.7117146849632263),
 ('treat', 0.6979131102561951),
 ('problems', 0.6909918785095215),
 ('confidence', 0.640256404876709),
 ('improvement', 0.6329619288444519),
 ('recovery', 0.6312937140464783),
 ('stress', 0.6191222071647644)]

In [24]:
embeddings_dash = []
for i in range(len(final)):
  for j in final[i]:
    embeddings_dash.append(model.wv[j])

In [25]:
len(embeddings_dash)

826

In [26]:
embeddings_dash[0]

array([-0.58677125, -0.10682375,  0.19841176,  0.33321166, -1.765612  ,
       -2.0114477 ,  0.01013915, -0.1547142 ,  0.5074882 , -1.3486637 ,
        0.43954125,  0.5858986 , -0.6046427 , -0.07314182, -0.8626982 ,
        1.936984  ,  0.29609096, -0.27069584,  0.5914859 , -0.36061913,
        0.19103536,  0.31832504, -0.16985609, -0.29192543, -0.8776009 ,
        0.27450293, -0.9667868 , -1.1509514 , -0.29041114, -0.20419437,
        0.21364865, -0.2805836 ], dtype=float32)

In [27]:
import numpy as np

In [28]:
# for i in range(len(embeddings_dash)):
#   embeddings_dash[i] = np.pad(embeddings_dash[i],(6,6)) #when we one hot encoded the asanas, its number is elements were 32. therefore we pad 6 zeros in front and 6 at the back.

In [29]:
len(embeddings_dash[0])

32

In [30]:
embeddings_dash[0]

array([-0.58677125, -0.10682375,  0.19841176,  0.33321166, -1.765612  ,
       -2.0114477 ,  0.01013915, -0.1547142 ,  0.5074882 , -1.3486637 ,
        0.43954125,  0.5858986 , -0.6046427 , -0.07314182, -0.8626982 ,
        1.936984  ,  0.29609096, -0.27069584,  0.5914859 , -0.36061913,
        0.19103536,  0.31832504, -0.16985609, -0.29192543, -0.8776009 ,
        0.27450293, -0.9667868 , -1.1509514 , -0.29041114, -0.20419437,
        0.21364865, -0.2805836 ], dtype=float32)

In [31]:
final[0][0]

'positive'

In [32]:
import numpy as np
embeddings_dash = np.array(embeddings_dash)

In [33]:
embeddings_dash

array([[-0.58677125, -0.10682375,  0.19841176, ..., -0.20419437,
         0.21364865, -0.2805836 ],
       [-0.53367674, -0.14822549,  0.05528077, ..., -0.14450216,
         0.06095918, -0.17865306],
       [-0.492658  , -0.0853558 , -0.04126494, ..., -0.01724119,
        -0.06504118, -0.07188819],
       ...,
       [-0.47855735,  0.6670576 ,  1.0879058 , ..., -1.2405812 ,
        -0.8044246 ,  0.94287115],
       [-0.529387  ,  0.10425805,  0.08423693, ..., -1.7209015 ,
        -1.2575287 ,  1.0705081 ],
       [-1.4526618 , -0.93250334,  0.8027452 , ..., -0.75888187,
        -0.6904216 ,  0.7523569 ]], dtype=float32)

In [34]:
def one_hot(array):
    unique, inverse = np.unique(array, return_inverse=True)
    onehot = np.eye(unique.shape[0])[inverse]
    return onehot

In [35]:
arr = one_hot(connected_dataset)

In [36]:
output = arr

In [37]:
output

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
len(output)

826

In [39]:
input = embeddings_dash

In [40]:
len(input)

826

In [41]:
input.shape

(826, 32)

In [42]:
output.shape = input.shape

In [43]:
output.shape

(826, 32)

In [44]:
import tensorflow as tf

In [45]:
ann = tf.keras.models.Sequential()

In [46]:
ann.add(tf.keras.layers.Dense(220, activation='relu'))

In [47]:
ann.add(tf.keras.layers.Dense(units=32, activation='softmax'))

In [48]:
ann.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [49]:
ann.fit(input, output, batch_size = 5, epochs = 100)

Epoch 1/100
166/166 [==============================] - 1s 2ms/step - loss: 3.0648 - accuracy: 0.2131
Epoch 2/100
166/166 [==============================] - 0s 2ms/step - loss: 2.1302 - accuracy: 0.3983
Epoch 3/100
166/166 [==============================] - 0s 2ms/step - loss: 1.7699 - accuracy: 0.3923
Epoch 4/100
166/166 [==============================] - 0s 2ms/step - loss: 1.6649 - accuracy: 0.3898
Epoch 5/100
166/166 [==============================] - 0s 2ms/step - loss: 1.6171 - accuracy: 0.4007
Epoch 6/100
166/166 [==============================] - 0s 2ms/step - loss: 1.5905 - accuracy: 0.3886
Epoch 7/100
166/166 [==============================] - 0s 2ms/step - loss: 1.5599 - accuracy: 0.3995
Epoch 8/100
166/166 [==============================] - 0s 2ms/step - loss: 1.5473 - accuracy: 0.4007
Epoch 9/100
166/166 [==============================] - 0s 2ms/step - loss: 1.5357 - accuracy: 0.3874
Epoch 10/100
166/166 [==============================] - 0s 2ms/step - loss: 1.5326 - accura

In [50]:
test = []
test.append(model.wv['pain'])
test.append(model.wv['peacock'])
test = np.array(test)
test

array([[-0.9048441 , -0.5164918 ,  0.4251148 , -0.04966326, -0.35435683,
        -0.9933572 ,  0.07834414, -0.46734032,  0.37291723, -0.88784313,
         0.7980336 ,  0.39848676, -0.17991734, -0.60713357,  1.4567273 ,
         1.6070306 ,  0.4561262 , -0.14254999, -0.42534345,  0.59821624,
        -0.79765445,  1.5985252 , -0.6153358 ,  0.5582263 , -0.17120564,
        -0.7989929 ,  0.7456789 ,  1.4397846 ,  0.4617833 , -1.4826574 ,
        -0.71463364, -0.5288116 ],
       [-1.1930896 ,  0.25441438, -0.40470544,  0.12316014, -0.9836359 ,
         0.63438654,  0.6004929 ,  0.9193934 , -0.18876122,  0.19697443,
        -0.09551071,  1.127051  ,  0.09923577, -0.94688296, -0.54910517,
        -0.6908234 ,  0.18025811,  0.25247133, -0.4351236 , -0.01446969,
        -1.0077295 ,  0.7170416 ,  0.8104901 ,  0.00421384, -1.4159031 ,
         1.0519634 , -1.1560403 , -0.58158475, -1.4788368 , -0.64733666,
         1.268655  ,  0.06897409]], dtype=float32)

In [51]:
for i in range(len(asana_dataset['asanas'])):
  for j in ann.predict(test):
    if i == np.argmax(j):
      print(asana_dataset['asanas'][i])

Matsyendrasana
Hastasana
